### ISSUE TITLE
YOLOv8 - classes invertion in data.yaml

### ISSUE THREAD

**Issue by erwanlenagard** [roboflow/roboflow-python#100]
Hello, 

I'd like to report a minor bug. I've annotated a dataset with Roboflow. I exported my data in YOLOv8 format but 2 classes are inverted in data.yaml. The model have been trained sucessfully but when I display the labels on images, they are inverted...

```
train: ../train/images
val: ../valid/images
test: ../test/images

nc: 9
names: ['Bibendum', 'Casquette', 'Dunlop', 'Goodyear', 'Michelin bibendum', **'Michelin logo carre', 'Michelin logo',** 'Michelin sept', 'Pneu']

roboflow:
  workspace: tmf
  project: michelin-gt
  version: 11
  license: CC BY 4.0
  url: https://universe.roboflow.com/tmf/michelin-gt/dataset/11
```

I expected : 
names: ['Bibendum', 'Casquette', 'Dunlop', 'Goodyear', 'Michelin bibendum', **'Michelin logo', 'Michelin logo carre'** 'Michelin sept', 'Pneu']

Here are the augmentations / preprocessing steps I choose in Roboflow before exporting : 

PREPROCESSING
Resize: Stretch to 640x640
Modify Classes: 4 remapped, 3 dropped

AUGMENTATIONS
Outputs per training example: 3
Rotation: Between -15° and +15°
Saturation: Between -25% and +25%
Brightness: Between -25% and +25%
Exposure: Between -25% and +25%
